apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: spring-docker-kuber-test
spec:
  selector:
    matchLabels:
      app: spring-docker-kuber-test
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-docker-kuber-test
    spec:
      containers:
        - name: spring-docker-kuber-test
          image: akramdev1/spring-docker-kuber_test_1:latest  # Image that will be used to containers in the cluster
          imagePullPolicy: always
          ports:
            - containerPort: 8761
---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: spring-docker-kuber-test
spec:
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
  selector:
    app: spring-docker-kuber-test
  ports:
    - protocol: "TCP"
      port: 8761 # The port that the service is running on in the cluster
      targetPort: 8761 # The port exposed by the service
